// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ops} from '../models';
import {jobs} from '../models';
import {ffmpeg} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function Convert(arg1:ops.ConvertParams):Promise<string>;

export function GetJob(arg1:string):Promise<jobs.Job>;

export function GetMetadata(arg1:string):Promise<ffmpeg.MediaInfo>;

export function RevealInFolder(arg1:string):Promise<void>;

export function SelectInputFile():Promise<string>;

export function SelectOutputPath(arg1:string):Promise<string>;

export function SuggestOutputName(arg1:string,arg2:string):Promise<string>;
