// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {license} from '../models';
import {ops} from '../models';
import {jobs} from '../models';
import {ffmpeg} from '../models';
import {settings} from '../models';

export function Activate(arg1:string):Promise<license.Status>;

export function AddWatermark(arg1:ops.WatermarkParams):Promise<string>;

export function AppVersion():Promise<string>;

export function CancelJob(arg1:string):Promise<void>;

export function ChangeSpeed(arg1:ops.SpeedParams):Promise<string>;

export function Compress(arg1:ops.CompressParams):Promise<string>;

export function Convert(arg1:ops.ConvertParams):Promise<string>;

export function Deactivate():Promise<void>;

export function ExtractAudio(arg1:ops.ExtractParams):Promise<string>;

export function GetJob(arg1:string):Promise<jobs.Job>;

export function GetMetadata(arg1:string):Promise<ffmpeg.MediaInfo>;

export function GetPreferences():Promise<settings.Preferences>;

export function LicenseStatus():Promise<license.Status>;

export function MakeGif(arg1:ops.GifParams):Promise<string>;

export function Merge(arg1:ops.MergeParams):Promise<string>;

export function OpenPurchasePage():Promise<void>;

export function RevealInFolder(arg1:string):Promise<void>;

export function Rotate(arg1:ops.RotateParams):Promise<string>;

export function SavePreferences(arg1:settings.Preferences):Promise<settings.Preferences>;

export function SelectFolder():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectInputFile():Promise<string>;

export function SelectInputFiles():Promise<Array<string>>;

export function SelectOutputPath(arg1:string):Promise<string>;

export function SuggestOutput(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Thumbnail(arg1:string):Promise<string>;

export function Trim(arg1:ops.TrimParams):Promise<string>;
