// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['main']['App']['Activate'](arg1);
}

export function AddWatermark(arg1) {
  return window['go']['main']['App']['AddWatermark'](arg1);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function ChangeSpeed(arg1) {
  return window['go']['main']['App']['ChangeSpeed'](arg1);
}

export function Compress(arg1) {
  return window['go']['main']['App']['Compress'](arg1);
}

export function Convert(arg1) {
  return window['go']['main']['App']['Convert'](arg1);
}

export function Deactivate() {
  return window['go']['main']['App']['Deactivate']();
}

export function ExtractAudio(arg1) {
  return window['go']['main']['App']['ExtractAudio'](arg1);
}

export function GetJob(arg1) {
  return window['go']['main']['App']['GetJob'](arg1);
}

export function GetMetadata(arg1) {
  return window['go']['main']['App']['GetMetadata'](arg1);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function LicenseStatus() {
  return window['go']['main']['App']['LicenseStatus']();
}

export function MakeGif(arg1) {
  return window['go']['main']['App']['MakeGif'](arg1);
}

export function Merge(arg1) {
  return window['go']['main']['App']['Merge'](arg1);
}

export function OpenPurchasePage() {
  return window['go']['main']['App']['OpenPurchasePage']();
}

export function RevealInFolder(arg1) {
  return window['go']['main']['App']['RevealInFolder'](arg1);
}

export function Rotate(arg1) {
  return window['go']['main']['App']['Rotate'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectInputFiles() {
  return window['go']['main']['App']['SelectInputFiles']();
}

export function SelectOutputPath(arg1) {
  return window['go']['main']['App']['SelectOutputPath'](arg1);
}

export function SuggestOutput(arg1, arg2, arg3) {
  return window['go']['main']['App']['SuggestOutput'](arg1, arg2, arg3);
}

export function Trim(arg1) {
  return window['go']['main']['App']['Trim'](arg1);
}
